### ISSUE TITLE
Whether this .ino file can be executable on Ccstudio

### ISSUE THREAD

**Issue by stan880219** [user79/JPEGcamera_MSP430#1]
Hi, I wanted to try this project on my launchpad(MSP430g2553),and my operating system is macos ,but I can only use the Ccstudio development environment. And I also can not execute the given code on Energia. If you had tried on the Ccstudio to do this project, Could you offer that to give me a hand? Thanks.

**Comment by user79** [comment]
Yes, I believe that I used Code Composer Studio to run this, with its option to import Energia sketches.  See https://hackaday.com/2014/07/13/proper-debugging-for-energia-sketches/ 
I am not sure if Code Composer Studio still has this import option. 
Also, I think the MSP430G2553 may not have enough memory to properly run the SD-card code (needs 512 bytes just for the SD-card buffer array).  This is why I used a MSP430F5529.

**Comment by stan880219** [comment]
Hi, thank for your reply. My ccs version is latest (v12.1.0), but I can't
follow the  import Energia sketches method with your attaching url. I don't
know whether this function is removed or not. And then I am trying to
rewrite the main function in the ccs, but it occurred lots of library
problems, specially "energia.h", So if you are free, could you offer me
related ccs code?
Thank for your reminding, I will check the MSP430G2553's memory size, if
necessary, MSP430F5529 will be also acceptable for me!

Thanks,

Shao

user79 ***@***.***> 於 2022年10月1日 週六 清晨6:09寫道：

**Comment by user79** [comment]
I looked at this today. I was not able to get Energia sketches working with the latest version of CCS, even after following this advice to connect the downloaded Energia with CCS https://forum.43oh.com/topic/13173-energiacore/ .  I am not sure how to make this work with the latest version of CCS.  If you could get CCS to create or successfully build and run Energia sketches, then this code in this repository would probably work for you.  
Eventually, it would be good if we could re-work this demo to use other available libraries for RS232/UART and SPI communication rather than relying on Energia.  Sadly, I do not have the time right now to work on this.

**Comment by user79** [comment]
See also, https://e2e.ti.com/support/microcontrollers/msp-low-power-microcontrollers-group/msp430/f/msp-low-power-microcontroller-forum/704328/compiler-msp-exp430f5529-error-type-product-energia-core-v18-0-is-not-currently-installed-and-no-compatible-version-is-available-please-install-this-product-or-a-compatible-version

**Comment by user79** [comment]
Update: I discovered that CCS 12 no longer supports Energia.
https://e2e.ti.com/support/microcontrollers/arm-based-microcontrollers-group/arm-based-microcontrollers/f/arm-based-microcontrollers-forum/1132367/energia-cannot-find-energia-sketch-in-ccs-v12-file---new---project

We will have to rewrite this some day using a different set of libraries.

**Comment by stan880219** [comment]
Thanks a lot.

user79 ***@***.***> 於 2022年10月2日 週日 上午11:43寫道：

**Comment by stan880219** [comment]
Hi, after lots of test on Energia I got this problem:

Energia: 1.8.11E23 (Mac OS X), Board: "MSP-EXP430F5529LP"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1445014]

goroutine 1 [running]:
github.com/arduino/arduino-cli/legacy/builder.ResolveLibrary(0xc00013cc00,
0xc0003c3b83, 0x9, 0xc0003c3b83)
/Users/robertinant/go/src/
github.com/arduino/arduino-cli/legacy/builder/resolve_library.go:64 +0x1d4
github.com/arduino/arduino-cli/legacy/builder.findIncludesUntilDone(0xc00013cc00,
0xc00036aae0, 0x157dce0, 0xc00023e870, 0xc00041e390, 0xc00036ce00, 0x0)
/Users/robertinant/go/src/
github.com/arduino/arduino-cli/legacy/builder/container_find_includes.go:358
+0x3db
github.com/arduino/arduino-cli/legacy/builder.(*ContainerFindIncludes).Run(0x1bb42b0,
0xc00013cc00, 0x1bb42b0, 0x0)
/Users/robertinant/go/src/
github.com/arduino/arduino-cli/legacy/builder/container_find_includes.go:152
+0x4e6
github.com/arduino/arduino-cli/legacy/builder.runCommands(0xc00013cc00,
0xc0001b3c20, 0x20, 0x20, 0x1, 0x101663f, 0x2c0cb00)
/Users/robertinant/go/src/
github.com/arduino/arduino-cli/legacy/builder/builder.go:210 +0xdf
github.com/arduino/arduino-cli/legacy/builder.(*Builder).Run(0xc0000d7e70,
0xc00013cc00, 0x1bb41b0, 0xc00009d990)
/Users/robertinant/go/src/
github.com/arduino/arduino-cli/legacy/builder/builder.go:117 +0xd28
github.com/arduino/arduino-cli/legacy/builder.RunBuilder(...)
/Users/robertinant/go/src/
github.com/arduino/arduino-cli/legacy/builder/builder.go:226
main.main()
/Users/robertinant/go/src/github.com/arduino/arduino-builder/main.go:398
+0x800
/private/var/folders/rj/zn5_64456zb346b82vhfpjr80000gn/T/AppTranslocation/7D251F03-7BDE-49BE-98B8-79A65CCFC5A8/d/Energia.app/Contents/Java/arduino-builder
returned 2
Error compiling for board MSP-EXP430F5529LP.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

 Have you ever encountered this problem before?
Thanks.

台師大張劭群 ***@***.***> 於 2022年10月3日 週一 下午2:07寫道：

**Comment by user79** [comment]
Hello,

Sorry, I do not remember encountering that error before.

Perhaps you can simplify your code to a smaller version and see if you still get that same error, then add back the other pieces of code bit by bit.

Or, you can import the needed parts of the Energia library into a Code Composer Studio project bit by bit, until it compiles, then use CCS debugger to help.

Tim
